// src/lib/teamOptimizer.ts
import pokemonData from "../data/pokemon.json";
import { detectArchetypes } from "./archetypeDetector";
import { evaluateTeam, type Pokemon, type PokemonBuild } from "./teamEvaluator";
import { fetchPokemonGameData, type LiveGameData } from "./pokeApi";

export type OptimizedTeamResult = {
    archetype: string;
    team: {
        name: string;
        build: PokemonBuild | null;
        buildName: string;
        types: string[];
        sprite: string;
        isAutoGenerated: boolean;
        stats: { name: string; base_stat: number }[];
    }[];
    score: number;
    evaluation: ReturnType<typeof evaluateTeam>;
};

const pokemonMap: Record<string, Pokemon> = Object.fromEntries(
    (pokemonData as unknown as Pokemon[]).map((pokemon) => [
        pokemon.name.toLowerCase(),
        pokemon
    ])
);

function getArchetypeBonus(team: string[], archetype: string): number {
    let bonus = 0;
    for (const pokemonName of team) {
        const pokemon = pokemonMap[pokemonName.toLowerCase()];
        if (!pokemon) continue;
        if (pokemon.archetypes.includes(archetype)) {
            bonus += 5;
        }
    }
    return bonus;
}

/**
 * Heuristic Generator: Creates a logical, stat-biased competitive setup 
 * for any non-curated species gathered out of the national pokedex.
 */
function generateDynamicFallbackBuild(liveData: LiveGameData | null): PokemonBuild {
    let build: PokemonBuild = {
        ability: "Pressure",
        item: "Leftovers",
        nature: "Hardy",
        evs: "252 HP / 252 Spe / 4 Def",
        moves: ["Protect", "Substitute", "Rest", "Sleep Talk"],
        teraType: "Normal"
    };

    if (liveData) {
        const atkStat = liveData.stats.find(s => s.name === "attack")?.base_stat || 0;
        const spaStat = liveData.stats.find(s => s.name === "special-attack")?.base_stat || 0;
        const isPhysical = atkStat > spaStat;

        build = {
            ability: liveData.abilities[0] || "Unknown",
            item: "Leftovers",
            nature: isPhysical ? "Adamant" : "Modest",
            evs: isPhysical ? "252 HP / 252 Atk / 4 Spe" : "252 HP / 252 SpA / 4 Spe",
            moves: ["Protect", "Substitute", "Tera Blast", isPhysical ? "Facade" : "Hyper Voice"],
            teraType: liveData.types[0] || "Normal"
        };
    }

    return build;
}

// Basic Beam Search implementation for VGC team optimization
async function runBeamSearchForArchetype(
    box: string[],
    targetArchetype: string,
    liveBoxData: Record<string, LiveGameData | null>
): Promise<OptimizedTeamResult> {
    const beamWidth = 40;

    let candidates: string[][] = box.map(p => [p]);

    for (let depth = 1; depth < 6; depth++) {
        const nextCandidates: { team: string[], score: number }[] = [];

        for (const team of candidates) {
            const available = box.filter(p => !team.includes(p));
            for (const candidate of available) {
                const newTeam = [...team, candidate];
                const evaluation = evaluateTeam(newTeam);
                const score = evaluation.score + getArchetypeBonus(newTeam, targetArchetype);

                nextCandidates.push({ team: newTeam, score });
            }
        }

        nextCandidates.sort((a, b) => b.score - a.score);
        candidates = nextCandidates.slice(0, beamWidth).map(c => c.team);
    }

    const bestTeamNames = candidates[0] || [];
    const finalEvaluation = evaluateTeam(bestTeamNames);
    const finalScore = finalEvaluation.score + getArchetypeBonus(bestTeamNames, targetArchetype);

    // Assemble layout profiles weaving curated frameworks vs generic fallback records
    const finalizedTeam = bestTeamNames.map((name) => {
        const pData = pokemonMap[name.toLowerCase()];
        const liveData = liveBoxData[name.toLowerCase()];

        let targetBuild = null;
        let buildName = "Auto-Generated Build";

        // Guaranteed to be an object, safely silencing TypeScript undefined errors
        const builds = pData?.builds || {};
        const hasBuilds = Object.keys(builds).length > 0;

        if (hasBuilds) {
            if (builds[targetArchetype]) {
                targetBuild = builds[targetArchetype];
                buildName = `${targetArchetype.charAt(0).toUpperCase() + targetArchetype.slice(1)} Variant`;
            } else {
                // Completely safe from TS errors because builds is definitely an object
                targetBuild = builds["goodstuff"] || Object.values(builds)[0] || null;

                const roles = pData?.roles || {};
                const primaryRole = Object.entries(roles)
                    .filter(([role]) => role !== "goodstuff")
                    .sort((a, b) => Number(b[1]) - Number(a[1]))[0]?.[0] || "Standard";

                buildName = primaryRole.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') + " Build";
            }
        } else {
            targetBuild = generateDynamicFallbackBuild(liveData);
        }

        return {
            name,
            build: targetBuild,
            buildName,
            types: liveData?.types || pData?.types || ["Normal"],
            sprite: liveData?.sprite || "",
            isAutoGenerated: !hasBuilds,
            stats: liveData?.stats || []
        };
    });

    return {
        archetype: targetArchetype,
        team: finalizedTeam,
        score: Math.max(0, finalScore),
        evaluation: finalEvaluation
    };
}

export async function optimizeTeam(box: string[]): Promise<OptimizedTeamResult[]> {
    if (box.length < 6) {
        throw new Error("Need at least 6 Pokémon in the box.");
    }

    const liveBoxData: Record<string, LiveGameData | null> = {};

    await Promise.all(
        box.map(async (pokemonName) => {
            const data = await fetchPokemonGameData(pokemonName);
            liveBoxData[pokemonName.toLowerCase()] = data;
        })
    );

    const archetypeScores = detectArchetypes(box);
    const topArchetypes = archetypeScores.filter((a) => a.score > 0).slice(0, 3).map((a) => a.archetype);

    if (topArchetypes.length === 0) {
        topArchetypes.push("goodstuff");
    }

    const recommendedStrategies: OptimizedTeamResult[] = [];
    for (const archetype of topArchetypes) {
        const result = await runBeamSearchForArchetype(box, archetype, liveBoxData);
        recommendedStrategies.push(result);
    }

    return recommendedStrategies;
}