// src/lib/teamOptimizer.ts
import { detectArchetypes } from "./archetypeDetector";
import { evaluateTeam, pokemonMap, type Pokemon, type PokemonBuild } from "./teamEvaluator";
import { fetchPokemonGameData, type LiveGameData } from "./pokeApi";

export type OptimizedTeamResult = {
    archetype: string;
    team: {
        name: string;
        build: PokemonBuild | null;
        buildName: string;
        types: string[];
        isAutoGenerated: boolean;
        stats: { name: string; base_stat: number }[];
    }[];
    score: number;
    evaluation: ReturnType<typeof evaluateTeam>;
};

function getArchetypeBonus(team: string[], archetype: string): number {
    let bonus = 0;
    for (const pokemonName of team) {
        const pokemon = pokemonMap[pokemonName.toLowerCase()];
        if (!pokemon) continue;
        if (pokemon.archetypes && pokemon.archetypes.includes(archetype)) {
            bonus += 5;
        }
    }
    return bonus;
}

/**
 * Checks if a Pokémon is functioning as a Mega Captain based on its item or name
 */
function isMegaCaptain(name: string, build: PokemonBuild | null, pData: Pokemon | undefined): boolean {
    const item = build?.item?.toLowerCase().replace(/[\s_-]/g, "") || "";
    const reqItem = pData?.requires_item?.toLowerCase().replace(/[\s_-]/g, "") || "";

    if (name.toLowerCase().includes("-mega")) return true;
    if (item.includes("ite") && item !== "eviolite") return true;
    if (reqItem && item === reqItem) return true;

    return false;
}

function generateDynamicFallbackBuild(liveData: LiveGameData | null): PokemonBuild {
    const defaultBuild: PokemonBuild = {
        ability: liveData?.abilities?.[0] || "Unknown Ability",
        item: "Leftovers",
        nature: "Hardy",
        evs: "252 HP / 4 Def / 252 Spe",
        moves: ["Protect", "Substitute", "Toxic", "Helping Hand"],
        teraType: liveData?.types?.[0] || "Normal"
    };

    if (!liveData || !liveData.stats) return defaultBuild;

    const statsMap = Object.fromEntries(liveData.stats.map(s => [s.name, s.base_stat]));
    const atk = statsMap["attack"] || 0;
    const spa = statsMap["special-attack"] || 0;
    const spe = statsMap["speed"] || 0;

    if (liveData.abilities.includes("intimidate")) defaultBuild.ability = "intimidate";
    else if (liveData.abilities.includes("prankster")) defaultBuild.ability = "prankster";

    if (atk > spa && atk > 90) {
        defaultBuild.nature = spe > 90 ? "Jolly" : "Adamant";
        defaultBuild.evs = "4 HP / 252 Atk / 252 Spe";
        defaultBuild.item = "Life Orb";
        defaultBuild.moves = ["Protect", "Close Combat", "Iron Head", "Facade"];
    } else if (spa > atk && spa > 90) {
        defaultBuild.nature = spe > 90 ? "Timid" : "Modest";
        defaultBuild.evs = "4 HP / 252 SpA / 252 Spe";
        defaultBuild.item = "Choice Specs";
        defaultBuild.moves = ["Hyper Voice", "Thunderbolt", "Earth Power", "Shadow Ball"];
    } else {
        defaultBuild.nature = "Bold";
        defaultBuild.evs = "252 HP / 128 Def / 128 SpD";
        defaultBuild.item = "Sitrus Berry";
    }

    if (liveData.abilities.includes("drizzle") || liveData.abilities.includes("primordial-sea")) {
        defaultBuild.moves.push("Hydro Pump");
    }

    defaultBuild.moves = Array.from(new Set(defaultBuild.moves)).slice(0, 4);
    while (defaultBuild.moves.length < 4) {
        defaultBuild.moves.push("Protect");
    }

    return defaultBuild;
}

/**
 * Bottom-up mechanical synergy calculator to evaluate micro-synergy configurations
 */
function getSynergyScore(team: string[], liveBoxData: Record<string, LiveGameData | null>): number {
    let synergy = 0;
    let hasDrizzle = false;
    let hasDrought = false;
    let hasTrickRoom = false;
    const teamTypes = new Set<string>();

    for (const name of team) {
        const lowerName = name.toLowerCase();
        const pData = pokemonMap[lowerName];
        const liveData = liveBoxData[lowerName];
        const buildKey = Object.keys(pData?.builds || {})[0] || "goodstuff";
        const build = pData?.builds && buildKey ? pData.builds[buildKey] : null;

        const ability = build?.ability?.toLowerCase() || liveData?.abilities?.[0]?.toLowerCase() || "";
        const moves = build?.moves?.map(m => m.toLowerCase()) || [];

        if (ability === "drizzle" || ability === "primordial-sea") hasDrizzle = true;
        if (ability === "drought" || ability === "desolate-land") hasDrought = true;
        if (moves.includes("trick room")) hasTrickRoom = true;

        liveData?.types?.forEach(t => teamTypes.add(t.toLowerCase()));
    }

    if (teamTypes.has("fire") && teamTypes.has("water") && teamTypes.has("grass")) synergy += 30;
    if (teamTypes.has("fairy") && teamTypes.has("dragon") && teamTypes.has("steel")) synergy += 30;

    for (const name of team) {
        const lowerName = name.toLowerCase();
        const pData = pokemonMap[lowerName];
        const liveData = liveBoxData[lowerName];
        const buildKey = Object.keys(pData?.builds || {})[0] || "goodstuff";
        const build = pData?.builds && buildKey ? pData.builds[buildKey] : null;

        const ability = build?.ability?.toLowerCase() || liveData?.abilities?.[0]?.toLowerCase() || "";
        const moves = build?.moves?.map(m => m.toLowerCase()) || [];
        const types = liveData?.types?.map(t => t.toLowerCase()) || [];
        
        let speed = 100;
        if (liveData?.stats) {
            const speStat = liveData.stats.find(s => s.name === "speed" || s.name === "spe");
            if (speStat) speed = speStat.base_stat;
        }

        if (hasDrizzle) {
            if (ability === "swift swim") synergy += 25;
            if (types.includes("water")) synergy += 10;
            if (moves.includes("hurricane") || moves.includes("thunder")) synergy += 15;
            if (types.includes("fire") || moves.includes("solar beam") || moves.includes("solarbeam")) synergy -= 15;
        }

        if (hasDrought) {
            if (ability === "chlorophyll" || ability === "protosynthesis" || ability === "solar-power") synergy += 25;
            if (types.includes("fire")) synergy += 10;
            if (types.includes("water")) synergy -= 15;
        }

        if (hasTrickRoom) {
            if (speed <= 60) synergy += 20;
            if (speed >= 100) synergy -= 20;
        }
    }

    return synergy;
}

export async function optimizeTeam(box: string[]): Promise<OptimizedTeamResult[]> {
    if (!box || box.length < 6) {
        throw new Error("Sandbox requires at least 6 unique entries to process.");
    }

    Object.keys(pokemonMap).forEach(key => {
        const p = pokemonMap[key];
        if (!p.roles || Object.keys(p.roles).length === 0) {
            p.roles = { goodstuff: 1 };
        }
        if (!p.archetypes || p.archetypes.length === 0) {
            p.archetypes = ["goodstuff"];
        }
        if (!p.builds) {
            p.builds = {};
        }
    });

    const filteredPool = Array.from(new Set(box));
    const liveBoxData: Record<string, LiveGameData | null> = {};

    await Promise.all(
        filteredPool.map(async (name) => {
            const data = await fetchPokemonGameData(name);
            liveBoxData[name.toLowerCase()] = data;
        })
    );

    filteredPool.forEach(name => {
        const lowerName = name.toLowerCase();
        let pData = pokemonMap[lowerName];
        const liveData = liveBoxData[lowerName];

        if (!pData) {
            pData = {
                name: name,
                types: liveData?.types || ["Normal"],
                archetypes: ["goodstuff"],
                roles: { goodstuff: 1 },
                builds: {}
            };
            pokemonMap[lowerName] = pData;
        }

        if (!pData.builds) pData.builds = {};

        if (Object.keys(pData.builds).length === 0) {
            pData.builds["goodstuff"] = generateDynamicFallbackBuild(liveData);
        }
    });

    const archetypeScores = detectArchetypes(box);
    const topArchetypes = archetypeScores
        .filter((a) => a.score > 0)
        .map((a) => a.archetype);

    if (topArchetypes.length === 0) {
        topArchetypes.push("goodstuff");
    }

    const recommendedStrategies: OptimizedTeamResult[] = [];

    for (const archetype of topArchetypes) {
        let candidates = filteredPool.filter(name => {
            const p = pokemonMap[name.toLowerCase()];
            return p && (p.archetypes.includes(archetype) || p.archetypes.includes("goodstuff"));
        });

        if (candidates.length < 6) {
            candidates = [...filteredPool];
        }

        let beams: string[][] = [[]];
        const beamWidth = 3;

        for (let size = 0; size < 6; size++) {
            let nextBeams: { team: string[]; score: number }[] = [];

            for (const currentTeam of beams) {
                for (const candidate of candidates) {
                    if (currentTeam.includes(candidate)) continue;

                    const nextTeam = [...currentTeam, candidate];
                    const evaluation = evaluateTeam(nextTeam);
                    
                    const synergyScore = getSynergyScore(nextTeam, liveBoxData);
                    let currentScore = evaluation.score + getArchetypeBonus(nextTeam, archetype) + synergyScore;

                    let megaCount = 0;
                    for (const memberName of nextTeam) {
                        const pData = pokemonMap[memberName.toLowerCase()];
                        const buildKey = Object.keys(pData?.builds || {})[0] || "goodstuff";
                        const activeBuild = pData?.builds && buildKey ? pData.builds[buildKey] : null;
                        if (isMegaCaptain(memberName, activeBuild, pData)) {
                            megaCount++;
                        }
                    }
                    if (megaCount > 1) {
                        currentScore -= 150;
                    }

                    nextBeams.push({ team: nextTeam, score: currentScore });
                }
            }

            nextBeams.sort((a, b) => b.score - a.score);
            beams = nextBeams.slice(0, beamWidth).map(b => b.team);
        }

        // Return multiple team branches generated from our multi-beam width path
        for (const bestTeamNames of beams) {
            if (!bestTeamNames || bestTeamNames.length < 6) continue;

            const finalTeam = bestTeamNames.map(name => {
                const pData = pokemonMap[name.toLowerCase()];
                const liveData = liveBoxData[name.toLowerCase()];

                const buildKey = Object.keys(pData?.builds || {})[0];
                const originalBuild = buildKey ? pData.builds[buildKey] : null;

                const isAuto = !originalBuild || Object.keys(pData.builds).length === 0 || buildKey === "goodstuff";

                return {
                    name: pData?.name || name,
                    build: originalBuild || (pData?.builds?.["goodstuff"] || null),
                    buildName: buildKey || "goodstuff",
                    types: pData?.types || liveData?.types || ["Normal"],
                    isAutoGenerated: isAuto,
                    stats: liveData?.stats || []
                };
            });

            const finalEvaluation = evaluateTeam(bestTeamNames);
            const synergyScore = getSynergyScore(bestTeamNames, liveBoxData);

            recommendedStrategies.push({
                archetype: archetype,
                team: finalTeam,
                score: finalEvaluation.score + getArchetypeBonus(bestTeamNames, archetype) + synergyScore,
                evaluation: finalEvaluation
            });
        }
    }

    return recommendedStrategies.sort((a, b) => b.score - a.score).slice(0, 4);
}